# -*- coding: utf-8 -*-
"""GetOldTweets3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IfXenGTM7FNAzBrxjeev-SZ1XoHXw5Cs
"""



from google.colab import drive
drive.mount('/content/drive')

import GetOldTweets3 as got


def get_tweets():
    tweetCriteria = got.manager.TweetCriteria().setQuerySearch('Nigeria food crisis') \
                                           .setSince("2021-01-01") \
                                           .setUntil("2021-06-30") \
                                           .setMaxTweets(1)
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
    print(tweet.text)
    
  
get_tweets()